### ISSUE TITLE
Add example for server-side validation

### ISSUE THREAD

**Issue by getflourish** [jessekorzan/rUhuman#1]
I agree that CAPTCHAs are boring and it would be awesome to have better ways to deal with it. But a client-side CAPTCHA won’t help to prevent bots from submitting a form.

Any bot can come around and do this: 

`$(".btn").attr("disabled", false).trigger("click")`

I think you need to at least validate that on a server. It’s not that simple and could be misleading to people thinking this script would actually prevent bots.

**Comment by jessekorzan** [comment]
Challenge... accepted.

**Comment by jessekorzan** [comment]
Ok.  Done. Still in the spirit of simpl. Check out the ghetto PHP example.
